# Generated by Django 4.2.5 on 2023-10-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(help_text='Enter date in DD/MM/YYYY format')),
                ('time', models.TimeField(help_text='Enter time in HH:MM format')),
                ('description', models.TextField()),
                ('location', models.CharField(default='Your Event Location', max_length=100)),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('capacity', models.PositiveIntegerField(default=100, help_text='Maximum number of attendees allowed for this event')),
                ('is_attendance_capture_ready', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
